# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='titutlo',
            new_name='titulo',
        ),
    ]
